<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Shared\Domain\Shared.Domain\Shared.Domain.csproj" />
      <ProjectReference Include="..\..\Domain\Domain\Domain.csproj" />
      <ProjectReference Include="..\..\Infrastructure\Infrastructure.Minio\Infrastructure.Minio.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" Version="15.1.0" />
    </ItemGroup>

</Project>
